use_frameworks!

# plugin 'cocoapods-imy-bin'
# use_binaries!

platform :ios, '9.0'

target 'BinaryDemo' do
  source 'git@git.17usoft.com:wireless-bus/iOS_CheBaDa_Specs_Source.git'
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'CBDConfig'
  pod 'CBDNetworkEngine'
end
